version: '3.7'
name: beny
services:
  nginx:
    container_name: nginx
    image: nginx:1.27.0
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - nginx-server-network
    depends_on:
      - frontend
      - backend
  frontend:
    container_name: frontend
    image: node:20.15.1
    volumes:
      - ../../frontend:/usr/src/app
    working_dir: /usr/src/app
    entrypoint:
      - /bin/bash
      - -c
    command:
      - npm install && npm run dev
    networks:
      - nginx-server-network
  backend:
    container_name: backend
    build:
      context: ../../backend
      dockerfile: Dockerfile
    volumes:
      - ../../backend:/rails
    environment:
      SECRET_KEY_BASE: 005f239a82a3ff4f04ca437cb23192d2
      DATABASE_URL: postgres://postgres:password@postgres:5432/beny_back_prod
    networks:
      - nginx-server-network
      - postgres-network
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:14.12
    container_name: postgres
    environment:
      POSTGRES_DB: beny_back_prod
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db:/var/lib/postgresql/data'
    networks:
      - nginx-server-network
      - postgres-network
    ports:
      - "5432:5432"

networks:
  postgres-network:
    name: postgres-network
  nginx-server-network:
    name: nginx-server-network
    driver: bridge

volumes:
  db:
